version: "3.7"
services:

  item-db:
    container_name : item-db
    image: mongo:3
    ports:
      - 27017:27017
    volumes:
      - app-db:/data/db
    networks:
      - item-app


  item-app:
    container_name: item-app
    image: item-app:v1
    command: sh -c "npm install --production --unsafe-perm && npm run build && npm run start"
    ports:
      - 80:8080
    networks:
      - item-app


volumes:
  app-db:
    name: app-db

networks:
  item-app:
    driver: bridge 